const express = require('express')
const router = express.Router()
const accountController = require('../controller/account.controller.js')

/**
 * @swagger
 * /admin/dashboard/{token}:
 *   get:
 *     summary: Retrieve dashboard statistics for a manager's hotels
 *     description: Fetches dashboard data for a manager based on their token. The data includes hotel details, room availability, booking status, and total revenue across all managed hotels.
 *     tags:
 *       - Dashboard
 *     parameters:
 *       - in: path
 *         name: token
 *         required: true
 *         schema:
 *           type: string
 *         description: The authentication token of the manager to retrieve data for.
 *     responses:
 *       200:
 *         description: Successfully fetched dashboard data
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Dashboard data fetched successfully"
 *                 data:
 *                   type: object
 *                   properties:
 *                     totalHotels:
 *                       type: integer
 *                       example: 5
 *                       description: The total number of hotels managed by the manager.
 *                     totalRooms:
 *                       type: integer
 *                       example: 120
 *                       description: The total number of rooms across all hotels.
 *                     totalBookings:
 *                       type: integer
 *                       example: 200
 *                       description: The total number of bookings across all hotels.
 *                     pendingBookings:
 *                       type: integer
 *                       example: 30
 *                       description: The total number of pending bookings.
 *                     paidBookings:
 *                       type: integer
 *                       example: 150
 *                       description: The total number of bookings with paid status.
 *                     confirmedBookings:
 *                       type: integer
 *                       example: 120
 *                       description: The total number of confirmed bookings.
 *                     totalRevenue:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           hotelId:
 *                             type: string
 *                             example: "hotel_123"
 *                             description: The ID of the hotel.
 *                           totalRevenue:
 *                             type: number
 *                             example: 50000
 *                             description: The total revenue generated by the hotel.
 *                     hotelRoomData:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           hotelId:
 *                             type: string
 *                             example: "hotel_123"
 *                             description: The ID of the hotel.
 *                           totalRooms:
 *                             type: integer
 *                             example: 50
 *                             description: The total number of rooms in the hotel.
 *                           bookedRooms:
 *                             type: integer
 *                             example: 40
 *                             description: The number of booked rooms in the hotel.
 *                           freeRooms:
 *                             type: integer
 *                             example: 10
 *                             description: The number of free rooms in the hotel.
 *       404:
 *         description: Manager not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Manager not found"
 *       500:
 *         description: Internal server error while fetching dashboard data
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "An error occurred while fetching dashboard data"
 */
router.get('/dashboard/:adminId', accountController.getDashboardData)

/**
 * @swagger
 * /admin/login:
 *   post:
 *     summary: Admin login
 *     description: Log in an admin account using email and password.
 *     tags:
 *       - Admin
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 example: "admin@example.com"
 *               password:
 *                 type: string
 *                 example: "your_password"
 *     responses:
 *       200:
 *         description: Login successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Login successful"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 token:
 *                   type: string
 *                   example: "your_generated_token"
 *                 data:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                       example: "admin_123"
 *                     fullName:
 *                       type: string
 *                       example: "Admin User"
 *                     email:
 *                       type: string
 *                       example: "admin@example.com"
 *                     phone:
 *                       type: string
 *                       example: "123-456-7890"
 *                     address:
 *                       type: string
 *                       example: "123 Admin St, Admin City, Admin State"
 *                     dateOfBirth:
 *                       type: string
 *                       format: date
 *                       example: "1980-01-01"
 *                     userName:
 *                       type: string
 *                       example: "adminuser"
 *       400:
 *         description: Invalid login credentials
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Email not found"
 *                 status:
 *                   type: integer
 *                   example: 400
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Login failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.post('/login', accountController.adminLogin)

/**
 * @swagger
 * /admin/me:
 *   get:
 *     summary: Get current admin account details
 *     description: Retrieve the details of the current admin account using the token provided in the query parameters.
 *     tags:
 *       - Admin
 *     parameters:
 *       - in: query
 *         name: tokenID
 *         required: true
 *         schema:
 *           type: string
 *           example: "your_token_here"
 *     responses:
 *       200:
 *         description: Account details retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account details"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                       example: "admin_123"
 *                     fullName:
 *                       type: string
 *                       example: "Admin User"
 *                     email:
 *                       type: string
 *                       example: "admin@example.com"
 *                     phone:
 *                       type: string
 *                       example: "123-456-7890"
 *                     address:
 *                       type: string
 *                       example: "123 Admin St, Admin City, Admin State"
 *                     dateOfBirth:
 *                       type: string
 *                       format: date
 *                       example: "1980-01-01"
 *                     userName:
 *                       type: string
 *                       example: "adminuser"
 *       400:
 *         description: Account not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account not found"
 *                 status:
 *                   type: integer
 *                   example: 400
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get account failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/me', accountController.adminMe)

/**
 * @swagger
 * /admin/superAdmin/accounts:
 *   get:
 *     summary: Get all accounts
 *     description: Fetch all accounts from the database.
 *     tags:
 *       - SuperAdmin
 *     responses:
 *       200:
 *         description: Accounts fetched successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Accounts fetched successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       _id:
 *                         type: string
 *                         example: "account_123"
 *                       email:
 *                         type: string
 *                         example: "user@example.com"
 *                       role:
 *                         type: string
 *                         example: "admin"
 *                       token:
 *                         type: string
 *                         example: "unique_token_123"
 *       500:
 *         description: Failed to fetch accounts
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get accounts failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/superAdmin/accounts', accountController.getAccounts)

/**
 * @swagger
 * /admin/superAdmin/account:
 *   post:
 *     summary: Create a new account
 *     description: Create a new account with email, password, and role.
 *     tags:
 *       - SuperAdmin
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 example: "newuser@example.com"
 *               password:
 *                 type: string
 *                 example: "password123"
 *               role:
 *                 type: string
 *                 example: "admin"
 *     responses:
 *       200:
 *         description: Account created successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account created successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                       example: "account_123"
 *                     email:
 *                       type: string
 *                       example: "newuser@example.com"
 *                     role:
 *                       type: string
 *                       example: "admin"
 *                     token:
 *                       type: string
 *                       example: "unique_token_123"
 *       500:
 *         description: Failed to create account
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Create account failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.post('/superAdmin/account', accountController.createAccount)

/**
 * @swagger
 * /admin/superAdmin/account/{accountId}:
 *   put:
 *     summary: Update an account
 *     description: Update the details of an account by its ID.
 *     tags:
 *       - Admin
 *     parameters:
 *       - name: accountId
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *           example: "account_123"
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 example: "updateduser@example.com"
 *               password:
 *                 type: string
 *                 example: "newpassword123"
 *               role:
 *                 type: string
 *                 example: "superadmin"
 *     responses:
 *       200:
 *         description: Account updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account updated successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                       example: "account_123"
 *                     email:
 *                       type: string
 *                       example: "updateduser@example.com"
 *                     role:
 *                       type: string
 *                       example: "superadmin"
 *       400:
 *         description: Account not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account not found"
 *                 status:
 *                   type: integer
 *                   example: 400
 *       500:
 *         description: Failed to update account
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Update account failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.put('/superAdmin/account/:accountId', accountController.updateAccount)

/**
 * @swagger
 * /admin/superAdmin/account/{accountId}:
 *   delete:
 *     summary: Delete an account
 *     description: Delete an account by its ID.
 *     tags:
 *       - Admin
 *     parameters:
 *       - name: accountId
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *           example: "account_123"
 *     responses:
 *       200:
 *         description: Account deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account deleted successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *       400:
 *         description: Account not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Account not found"
 *                 status:
 *                   type: integer
 *                   example: 400
 *       500:
 *         description: Failed to delete account
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Delete account failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.delete('/superAdmin/account/:accountId', accountController.deleteAccount)

/**
 * @swagger
 * /admin/superAdmin/displayedPosts:
 *   get:
 *     summary: Get the top 5 most visited cities' posts
 *     description: Fetches posts related to the top 5 cities with the most bookings.
 *     tags:
 *       - SuperAdmin
 *     responses:
 *       200:
 *         description: Displayed posts fetched successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Displayed posts fetched successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       _id:
 *                         type: string
 *                         example: "post_123"
 *                       title:
 *                         type: string
 *                         example: "Top tourist destinations"
 *                       content:
 *                         type: string
 *                         example: "Explore the best places to visit in the city."
 *                       keyword:
 *                         type: array
 *                         items:
 *                           type: string
 *                         example: ["New York", "Los Angeles", "Paris"]
 *       500:
 *         description: Failed to fetch displayed posts
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get displayed posts failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/superAdmin/displayPost', accountController.getDisplayedPosts)

/**
 * @swagger
 * /admin/superAdmin/displayedPlaces:
 *   get:
 *     summary: Get the top 5 most visited countries' posts
 *     description: Fetches posts related to the top 5 countries with the most bookings.
 *     tags:
 *       - SuperAdmin
 *     responses:
 *       200:
 *         description: Displayed places fetched successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Displayed places fetched successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       _id:
 *                         type: string
 *                         example: "post_123"
 *                       title:
 *                         type: string
 *                         example: "Top countries to visit"
 *                       content:
 *                         type: string
 *                         example: "Discover the best countries to visit for a vacation."
 *                       keyword:
 *                         type: array
 *                         items:
 *                           type: string
 *                         example: ["USA", "France", "Japan"]
 *       500:
 *         description: Failed to fetch displayed places
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get displayed places failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/superAdmin/displayPlace', accountController.getDisplayedPlaces)

/**
 * @swagger
 * /admin/superAdmin/displayedPostByID:
 *   get:
 *     summary: Get a specific post by ID
 *     description: Fetch a single post by its ID.
 *     tags:
 *       - SuperAdmin
 *     parameters:
 *       - in: query
 *         name: postId
 *         required: true
 *         description: The ID of the post to fetch.
 *         schema:
 *           type: string
 *           example: "post_123"
 *     responses:
 *       200:
 *         description: Post fetched successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Post fetched successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                       example: "post_123"
 *                     title:
 *                       type: string
 *                       example: "Best hotels in New York"
 *                     content:
 *                       type: string
 *                       example: "Here are the top hotels in New York."
 *       400:
 *         description: Post not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Post not found"
 *                 status:
 *                   type: integer
 *                   example: 400
 *       500:
 *         description: Failed to fetch the post
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get displayed post failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/superAdmin/displayPost/:postId', accountController.getDisplayedPostByID)

/**
 * @swagger
 * /admin/superAdmin/displayedHotels:
 *   get:
 *     summary: Get the top 5 most booked hotels
 *     description: Fetches the top 5 hotels with the most bookings.
 *     tags:
 *       - SuperAdmin
 *     responses:
 *       200:
 *         description: Displayed hotels fetched successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Displayed hotels fetched successfully"
 *                 status:
 *                   type: integer
 *                   example: 200
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       _id:
 *                         type: string
 *                         example: "hotel_123"
 *                       HotelName:
 *                         type: string
 *                         example: "Hotel Grand"
 *                       Address:
 *                         type: object
 *                         properties:
 *                           City:
 *                             type: string
 *                             example: "New York"
 *                           Country:
 *                             type: string
 *                             example: "USA"
 *                       Rating:
 *                         type: number
 *                         example: 4.5
 *       500:
 *         description: Failed to fetch displayed hotels
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "Get displayed hotels failed"
 *                 status:
 *                   type: integer
 *                   example: 500
 */
router.get('/superAdmin/displayHotel/:hotelId', accountController.getDisplayedHotels)

module.exports = router
